# Generated by Django 4.2.3 on 2023-10-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='customer_images'),
        ),
    ]
