# Generated by Django 4.2.3 on 2023-10-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_menu_alter_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='link',
            new_name='slug',
        ),
    ]
